# Generated by Django 5.1.2 on 2024-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
