# Generated by Django 5.1.2 on 2024-11-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='shown',
            field=models.BooleanField(default=False),
        ),
    ]
